
export default {
  SELECT_FOTO:         'SELECT_FOTO',
  PRODCUT_TO_CART:     'PRODCUT_TO_CART',
  ERASE_PRODUCT:       'ERASE_PRODUCT',
  CHANGE_QTTY:         'CHANGE_QTTY',
  CREACIONES_RECEIVED: 'CREACIONES_RECEIVED',
  FERIAS_RECEIVED:     'FERIAS_RECEIVED',
}
